version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - ./backend/.env
    environment:
      - PG_GATA=/var/lib/postgresql/data
    volumes:
      - $HOME/docker/volumes/postgres/:/var/lib/postgresql/data

  backend:
    container_name: backend
    env_file:
      - ./backend/.env
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app:rw
    expose:
      - 3001
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    restart: always

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/frontend:rw
    expose:
      - 3000
    depends_on:
      - backend
    restart: always
  
  nginx:
    container_name: proxy_nginx
    depends_on:
      - backend
      - frontend
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d:ro
      - ./backend/src/static/:/var/www/static:rw