version: '3.8'

services:
  nginx:
      image: nginx:alpine
      volumes:
        - ./backend/static/:/var/www/app/:rw
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      expose:
        - 80